version: '3.8'

services:
  backend:
    container_name: fastapi-backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
#     environment:
#       - ENV=development
#       - DEBUG=true
#     volumes:
#       - ./src:/app/src
#       - ./pyproject.toml:/app/pyproject.toml
#       - ./uv.lock:/app/uv.lock
#       - ./makefile:/app/makefile
#     networks:
#       - app-network
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 40s

# networks:
#   app-network:
#     driver: bridge